summon lc:dt_epsilon11c "§1§lMTF Epsilon-11 Commander"
summon lc:dt_eta10c "§b§lMTF Eta-10 Commander"
summon lc:dt_nu7c "§8§lMTF Nu-7 Commander"
summon lc:dt_beta7c "§6§lMTF Beta-7 Commander"
summon lc:dt_epsilon6c "§e§lMTF Epsilon-6 Commander"