summon lc:dt_cd_commander "§2§lChaos Delta Commander"
summon lc:dt_cd_leader "§a§lChaos Delta Leader 1"
summon lc:dt_cd_leader "§a§lChaos Delta Leader 2"
summon lc:dt_cd_leader "§a§lChaos Delta Leader 3"
summon lc:dt_cd_leader "§a§lChaos Delta Leader 4"